apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-to-container
  labels:
   app: kubernetes-to-container
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox:1.28
    env:
      - name: MY_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: MY_POD_SERVICE_ACCOUNT
        valueFrom:
          fieldRef:
            fieldPath: spec.serviceAccountName          
    command: 
    - 'sh'
    - '-c'
    - 'echo MY_POD_IP:$(MY_POD_IP)  MY_POD_NAME:$(MY_POD_NAME)  MY_POD_NAMESPACE:$(MY_POD_NAMESPACE)  MY_NODE_NAME:$(MY_NODE_NAME)  MY_POD_SERVICE_ACCOUNT:$(MY_POD_SERVICE_ACCOUNT) > /work-dir/index.html'
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
